version: '3.8'
services:
  step-by-tech-nodejs:
    container_name: step-by-tech-nodejs
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - .:/app
    command: sh -c "npm i && npm run dev"
    ports:
      - "7300:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
